//
//  UserLoginPresenter.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-04-15.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol UserLoginPresenterInput
{
  func presentLogin(response: UserLogin.Login.Response)
}

protocol UserLoginPresenterOutput: class
{
  func displayLogin(viewModel: UserLogin.Login.ViewModel)
}

class UserLoginPresenter: UserLoginPresenterInput
{
  weak var output: UserLoginPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentLogin(response: UserLogin.Login.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    let isLoginButtonEnabled = response.isPasswordValid && response.isUserNameEntered
    var loginButtonColour =  Constants.SystemColours.lightGreyColour
    if( isLoginButtonEnabled) {
      loginButtonColour = Constants.SystemColours.blueColour
    }
    
    let viewModel = UserLogin.Login.ViewModel(isUserLoggedIn: response.isUserLoggedIn,
                                              isPasswordSwitchOn: response.isPasswordValid,
                                              isLoginButtonEnabled: isLoginButtonEnabled,
                                              isForgotPasswordButtonEnabled: true,
                                              isSignupButtonEnabled: true,
                                              loginButtonColour: loginButtonColour)
    output.displayLogin(viewModel: viewModel)
  }
}
