//
//  UserLoginModels.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-04-15.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct UserLogin
{
  struct Login
  {
    struct Request
    {
      var username: String
      var password: String
      var requestType : RequestType
      
      enum RequestType
      {
        case loginRequest
        case updateView
      }
    }
    struct Response
    {
      var isUserNameEntered: Bool
      var isPasswordValid: Bool
      var isUserLoggedIn: Bool
      
    }
    struct ViewModel
    {
      var isUserLoggedIn: Bool
      var isPasswordSwitchOn: Bool
      var isLoginButtonEnabled: Bool
      var isForgotPasswordButtonEnabled: Bool
      var isSignupButtonEnabled: Bool
      var loginButtonColour: UIColor
    }
  }
}
