//
//  UserLoginConfigurator.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-04-15.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension UserLoginViewController: UserLoginPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension UserLoginInteractor: UserLoginViewControllerOutput
{
}

extension UserLoginPresenter: UserLoginInteractorOutput
{
}

class UserLoginConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = UserLoginConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: UserLoginViewController)
  {
    let router = UserLoginRouter()
    router.viewController = viewController
    
    let presenter = UserLoginPresenter()
    presenter.output = viewController
    
    let interactor = UserLoginInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
