//
//  FriendManagementPresenter.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-11-28.
//  Copyright (c) 2017 Enovi Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol FriendManagementPresenterInput {
    func presentFriends(response: FriendManagementScene.FetchFriends.Response)
}

protocol FriendManagementPresenterOutput: class {
    func displayFriends(response: FriendManagementScene.FetchFriends.ViewModel)
}

class FriendManagementPresenter: FriendManagementPresenterInput {
    
    weak var output: FriendManagementPresenterOutput?
    
    // MARK: Presentation logic
    func presentFriends(response: FriendManagementScene.FetchFriends.Response) {
        
    }
    
}
