//
//  FriendManagementViewController.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-11-28.
//  Copyright (c) 2017 Enovi Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol FriendManagementViewControllerInput {
    func displayFriends(response: FriendManagementScene.FetchFriends.ViewModel)
}

protocol FriendManagementViewControllerOutput {
    func fetchTakes(request: FriendManagementScene.FetchFriends.Request)
    func acceptFriendshipRequest(request: FriendManagementScene.AcceptFriendshipRequest.Request)
    func sendFriendshipRequest(request: FriendManagementScene.SendFriendshipRequest.Request)
}

class FriendManagementViewController: ReachabilityViewController,
UITableViewDelegate,
FriendManagementViewControllerInput {
    
    var output: FriendManagementViewControllerOutput?
    var router: FriendManagementRouter?
    
    var friendManagementTableViewDataSource = FriendManagementTableViewDataSource()
    
    @IBOutlet weak var friendManagementTableView: UITableView!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        FriendManagementConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        friendManagementTableViewDataSource.viewController = self
        friendManagementTableView.delegate = self
        
        fetchFriendsOnLoad()
    }
    
    // MARK: Requests
    
    func fetchFriendsOnLoad() {
        let request = FriendManagementScene.FetchFriends.Request(requestType: .fetchAll)
        output?.fetchTakes(request: request)
    }
    
    func fetchFriendsOnUpdate() {
        let request = FriendManagementScene.FetchFriends.Request(requestType: .fetchUpdate)
        output?.fetchTakes(request: request)
    }
    
    // MARK: Display logic
    func displayFriends(response: FriendManagementScene.FetchFriends.ViewModel) {
    }
    
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension FriendManagementViewController: FriendManagementPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
