//
//  FriendManagementInteractor.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-11-28.
//  Copyright (c) 2017 Enovi Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol FriendManagementInteractorInput {
    func fetchTakes(request: FriendManagementScene.FetchFriends.Request)
    func acceptFriendshipRequest(request: FriendManagementScene.AcceptFriendshipRequest.Request)
    func sendFriendshipRequest(request: FriendManagementScene.SendFriendshipRequest.Request)
}

protocol FriendManagementInteractorOutput {
    func presentFriends(response: FriendManagementScene.FetchFriends.Response)
}

protocol FriendManagementDataSource {
    
}

protocol FriendManagementDataDestination {
    
}

class FriendManagementInteractor: FriendManagementInteractorInput, FriendManagementDataSource, FriendManagementDataDestination {
    
    var output: FriendManagementInteractorOutput?
    
    // MARK: Business logic
    func fetchTakes(request: FriendManagementScene.FetchFriends.Request) {
        
    }
    
    func acceptFriendshipRequest(request: FriendManagementScene.AcceptFriendshipRequest.Request) {
        
    }
    
    func sendFriendshipRequest(request: FriendManagementScene.SendFriendshipRequest.Request) {
        
    }
    
}
