//
//  FriendManagementConfigurator.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-11-28.
//  Copyright (c) 2017 Enovi Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension FriendManagementInteractor: FriendManagementViewControllerOutput, FriendManagementRouterDataSource, FriendManagementRouterDataDestination {
}

extension FriendManagementPresenter: FriendManagementInteractorOutput {
}

class FriendManagementConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = FriendManagementConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: FriendManagementViewController) {
        
        let presenter = FriendManagementPresenter()
        presenter.output = viewController
        
        let interactor = FriendManagementInteractor()
        interactor.output = presenter
        
        let router = FriendManagementRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
