//
//  FriendManagementModels.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-11-28.
//  Copyright (c) 2017 Enovi Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct FriendManagementScene {
    
    struct AcceptFriendshipRequest {
        struct Request {
            var userName: String
        }
    }
    
    struct SendFriendshipRequest {
        struct Request {
            var userName: String
        }
    }
    
    struct FetchFriends {
        
        struct Request {
            var requestType: RequestType
            
            enum RequestType {
                case fetchAll
                case fetchUpdate
            }
        }
        
        struct Response {
            var friendsAndAcquaintances: [UserResponseModel]
            var otherUsers: [UserResponseModel]
            
            struct UserResponseModel {
                var userName: String
                var userRelationship: UserRelationship
            }
            
            enum UserRelationship {
                case friend
                case sentFriendshipRequest
                case receivedFriendshipRequest
                case notFriend
            }
        }
        
        struct ViewModel {
            var friendsAndAcquaintances: [UserViewModel]
            var otherUsers: [UserViewModel]
            
            struct UserViewModel {
                var userName: String
                var buttonTitle: String
                var isButtonEnabled: Bool
                var buttonColour: UIColor
            }
        }
    }
    
}
