//
//  SignupUserInteractor.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-04-15.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SignupUserInteractorInput
{
  func doSomething(request: SignupUser.Something.Request)
}

protocol SignupUserInteractorOutput
{
  func presentSomething(response: SignupUser.Something.Response)
}

class SignupUserInteractor: SignupUserInteractorInput
{
  var output: SignupUserInteractorOutput!
  var worker: SignupUserWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: SignupUser.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = SignupUserWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = SignupUser.Something.Response()
    output.presentSomething(response: response)
  }
}
