//
//  SignupUserConfigurator.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-04-15.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension SignupUserViewController: SignupUserPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension SignupUserInteractor: SignupUserViewControllerOutput
{
}

extension SignupUserPresenter: SignupUserInteractorOutput
{
}

class SignupUserConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = SignupUserConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: SignupUserViewController)
  {
    let router = SignupUserRouter()
    router.viewController = viewController
    
    let presenter = SignupUserPresenter()
    presenter.output = viewController
    
    let interactor = SignupUserInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
