//
//  SignupUserPresenter.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-04-15.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SignupUserPresenterInput
{
  func presentSignup(response: SignupUser.Signup.Response)
}

protocol SignupUserPresenterOutput: class
{
  func displaySignup(viewModel: SignupUser.Signup.ViewModel)
}

class SignupUserPresenter: SignupUserPresenterInput
{
  weak var output: SignupUserPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSignup(response: SignupUser.Signup.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    let isSignupButtonEnabled = response.isEmailValid && response.isUserNameValid && response.isPasswordValid
    let signupButtonColour = isSignupButtonEnabled ? Constants.systemBlueColour : Constants.systemLightGreyColour
    let viewModel = SignupUser.Signup.ViewModel(isEmailSwitchOn: response.isEmailValid,
                                                isUsernameSwitchOn: response.isUserNameValid,
                                                isPasswordSwitchOn: response.isPasswordValid,
                                                isSignupButtonEnabled: isSignupButtonEnabled,
                                                signupButtonColour: signupButtonColour)
    output.displaySignup(viewModel: viewModel)
  }
}
