//
//  SignupUserModels.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-04-15.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct SignupUser
{
  struct Signup
  {
    struct Request
    {
      var emailAddress: String
      var username: String
      var password: String
      var requestType: RequestType
      
      enum RequestType {
        case signupRequest
        case emailAddressVerification
        case userNameVerification
        case passwordVerification
      }
    }
    struct Response
    {
      var isEmailValid: Bool
      var isUserNameValid: Bool
      var isPasswordValid: Bool
    }
    struct ViewModel
    {
      var isEmailSwitchOn: Bool
      var isUsernameSwitchOn: Bool
      var isPasswordSwitchOn: Bool
      var isSignupButtonEnabled: Bool
      var signupButtonColour: UIColor
    }
  }
}
