//
//  SignupUserPresenter.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-04-15.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SignupUserPresenterInput
{
  func presentSomething(response: SignupUser.Something.Response)
}

protocol SignupUserPresenterOutput: class
{
  func displaySomething(viewModel: SignupUser.Something.ViewModel)
}

class SignupUserPresenter: SignupUserPresenterInput
{
  weak var output: SignupUserPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: SignupUser.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = SignupUser.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
