//
//  ChangePasswordModels.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-09-04.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ChangePassword {
    
    struct Request {
        var oldPassword: String
        var newPassword: String
        var reTypeNewPassword: String
    }
    
    struct Response {
        
        var responseType: ResponseType
        
        enum ResponseType {
            case success
            case newPasswordDoesNotMatch
            case oldPasswordIncorrect
        }
        
    }
    
    struct ViewModel {
    }
}
