//
//  ChangePasswordConfigurator.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-09-04.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ChangePasswordViewController: ChangePasswordPresenterOutput {
}

extension ChangePasswordInteractor: ChangePasswordViewControllerOutput {
}

extension ChangePasswordPresenter: ChangePasswordInteractorOutput {
}

class ChangePasswordConfigurator {
    // MARK: - Object lifecycle
    
    static let sharedInstance = ChangePasswordConfigurator()
    
    private init() {}
    
    // MARK: - Configuration
    
    func configure(viewController: ChangePasswordViewController) {
        let router = ChangePasswordRouter()
        router.viewController = viewController
        
        let presenter = ChangePasswordPresenter()
        presenter.output = viewController
        
        let interactor = ChangePasswordInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
