//
//  ChangePasswordInteractor.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-09-04.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ChangePasswordInteractorInput {
    func changePassword(request: ChangePassword.Request)
}

protocol ChangePasswordInteractorOutput {
    func presentSomething(response: ChangePassword.Response)
}

class ChangePasswordInteractor: ChangePasswordInteractorInput {
    
    var output: ChangePasswordInteractorOutput!
    var adminWorker = LoginWorker(loginStore: LoginBaasBoxStore())
    
    // MARK: - Business logic
    
    func changePassword(request: ChangePassword.Request) {
        
        if(request.newPassword == request.reTypeNewPassword) {
            let response =
                ChangePassword.Response(responseType: ChangePassword.Response.ResponseType.newPasswordDoesNotMatch)
            output.presentSomething(response: response)
        } else {
            adminWorker.changePassword(oldPassword: request.oldPassword, newPassword: request.newPassword,
                                       completion: {(isChangePasswordSuccess) -> Void in
                                        let responseType = isChangePasswordSuccess ? ChangePassword.Response.ResponseType.success : ChangePassword.Response.ResponseType.oldPasswordIncorrect
                                        self.output.presentSomething(response: ChangePassword.Response(responseType: responseType))
            })
        }
    }
}
