//
//  ChangePasswordPresenter.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-09-04.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ChangePasswordPresenterInput
{
  func presentSomething(response: ChangePassword.Response)
}

protocol ChangePasswordPresenterOutput: class
{
  func displaySomething(viewModel: ChangePassword.ViewModel)
}

class ChangePasswordPresenter: ChangePasswordPresenterInput
{
  weak var output: ChangePasswordPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: ChangePassword.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = ChangePassword.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
