//
//  ListChallengesConfigurator.swift
//  YourTakeClean
//
//  Created by John Buonassisi on 2017-03-28.
//  Copyright (c) 2017 JAB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ListChallengesViewControllerV2: ListChallengesPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension ListChallengesInteractor: ListChallengesViewControllerOutput {
}

extension ListChallengesPresenter: ListChallengesInteractorOutput {
}

class ListChallengesConfigurator
{
    // MARK: - Object lifecycle
    
    static let sharedInstance = ListChallengesConfigurator()
    
    private init() {}
    
    // MARK: - Configuration
    
    func configure(viewController: ListChallengesViewControllerV2) {
        let router = ListChallengesRouter()
        router.viewController = viewController
        
        let presenter = ListChallengesPresenter()
        presenter.output = viewController
        
        let interactor = ListChallengesInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
