//
//  ListChallengesModels.swift
//  YourTakeClean
//
//  Created by John Buonassisi on 2017-03-28.
//  Copyright (c) 2017 JAB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ListChallenges
{
  struct RefreshChallenges
  {
    struct Request
    {
      var challengeType: ChallengeRequestType
    }
  }
  
  struct FetchChallenges
  {
    struct Request
    {
      var challengeType: ChallengeRequestType
      var isChallengeAndImageLoadSeparated: Bool
    }
    
    struct ViewModel
    {
      
      struct DisplayedChallenge
      {
        var id: String
        var name: String
        var imageId: String
        var challengeImage: UIImage?
        var expiryLabel: String
        var totalVotesLabel: String
        var isDrawButtonEnabled: Bool
        var isVoteButton: Bool
      }
      
      enum ChallengeViewType: Int {
        case userChallenges = 0
        case friendChallenges = 1
        case noChallenges = 2
      }
      
      var challengeType: ChallengeViewType
      var displayedChallenges: [DisplayedChallenge]
      
    }
    
    struct Response
    {
      var challengeType: ChallengeResponseType
      var challenges: [ChallengeDto]
      
      enum ChallengeResponseType: Int {
        case userChallenges = 0
        case friendChallenges = 1
        case noChallenges = 2
      }
    }
  }
  
  enum ChallengeRequestType: Int {
    case userChallenges = 0
    case friendChallenges = 1
  }
}
