//
//  ListChallengesRouter.swift
//  YourTakeClean
//
//  Created by John Buonassisi on 2017-03-28.
//  Copyright (c) 2017 JAB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListChallengesRouterInput
{
  func navigateToTakesScene(with challengeId: String)
}

class ListChallengesRouter: ListChallengesRouterInput
{
  weak var viewController: ListChallengesViewController!
  
  // MARK: - Navigation
  
  func navigateToTakesScene(with challengeId: String)
  {
    // NOTE: Teach the router how to navigate to another scene. Some examples follow:
    
    // 1. Trigger a storyboard segue
    // viewController.performSegueWithIdentifier("ShowSomewhereScene", sender: nil)
    
    // 2. Present another view controller programmatically
    // viewController.presentViewController(someWhereViewController, animated: true, completion: nil)
    print("Navigating to Take List Scene")
    let ltvc = ListTakesViewController(challengeId: challengeId)
    viewController.navigationController?.pushViewController(ltvc, animated: true)
    
    // 3. Ask the navigation controller to push another view controller onto the stack
    // viewController.navigationController?.pushViewController(someWhereViewController, animated: true)
    
    // 4. Present a view controller from a different storyboard
    // let storyboard = UIStoryboard(name: "OtherThanMain", bundle: nil)
    // let someWhereViewController = storyboard.instantiateInitialViewController() as! SomeWhereViewController
    // viewController.navigationController?.pushViewController(someWhereViewController, animated: true)
  }
  
  func navigateToCreateTakeScene(challengeId: String, challengeImage: UIImage)
  {
    print("Navigating to Create Take Scene")
    let ctvc = CreateTakeViewController(challengeId: challengeId, challengeImage: challengeImage)
    viewController.navigationController?.pushViewController(ctvc, animated: true)
  }
  
  func navigateToSnapChallengeImageScene() {
    print("Navigating to Snap Challenge Scene")
    viewController.performSegue(withIdentifier: "PhotoPreviewViewController", sender: nil)
  }
  
  func navigateToAddFriendsScene() {
    print("Navigating to Add Friends Scene")
    viewController.performSegue(withIdentifier: "Friends", sender: nil)
  }
  
  // MARK: - Communication
  
  func passDataToNextScene(segue: UIStoryboardSegue)
  {
    // NOTE: Teach the router which scenes it can communicate with
    
    if segue.identifier == "ShowSomewhereScene" {
      passDataToSomewhereScene(segue: segue)
    }
  }
  
  func passDataToSomewhereScene(segue: UIStoryboardSegue)
  {
    // NOTE: Teach the router how to pass data to the next scene
    
    // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
    // someWhereViewController.output.name = viewController.output.name
  }
}
