//
//  PasswordVerificationConfigurator.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-10-08.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension PasswordVerificationViewController: PasswordVerificationPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension PasswordVerificationInteractor: PasswordVerificationViewControllerOutput {
}

extension PasswordVerificationPresenter: PasswordVerificationInteractorOutput {
}

class PasswordVerificationConfigurator {
    // MARK: - Object lifecycle

    static let sharedInstance = PasswordVerificationConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: PasswordVerificationViewController) {
        let router = PasswordVerificationRouter()
        router.viewController = viewController

        let presenter = PasswordVerificationPresenter()
        presenter.output = viewController

        let interactor = PasswordVerificationInteractor()
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
    }
}
