//
//  PasswordVerificationRouter.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-10-08.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PasswordVerificationRouterInput {
    func navigateToChangePasswordScene()
}

class PasswordVerificationRouter: PasswordVerificationRouterInput {
    
    weak var viewController: PasswordVerificationViewController!

    // MARK: - Navigation

    func navigateToChangePasswordScene() {
        viewController.performSegue(withIdentifier: Constants.SegueIdentifiers.PasswordVerificationScene.changePasswordSegue,
                                    sender: viewController)
    }
    
    func navigateToResetPasswordScene() {
        viewController.performSegue(withIdentifier: Constants.SegueIdentifiers.PasswordVerificationScene.resetPasswordSegue,
                                    sender: nil)
    }
    
    func presentAlert(title: String?, message: String?, actionTitle: String?) {
        let alert = UIAlertController(title: title,
                                      message: message,
                                      preferredStyle: .alert)
        let action = UIAlertAction(title: actionTitle,
                                   style: .default,
                                   handler: {
                                    (action: UIAlertAction!) in alert.dismiss(animated: true, completion: nil)})
        alert.addAction(action)
        present(viewControllerToPresent: alert, completion: nil)
    }
    
    func present(viewControllerToPresent: UIViewController, completion: (() -> Void)?) {
        self.viewController.present(viewControllerToPresent, animated: true, completion: completion)
    }

    // MARK: - Communication

    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with

        if segue.identifier == "ShowSomewhereScene" {
            passDataToSomewhereScene(segue: segue)
        }
    }

    func passDataToSomewhereScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router how to pass data to the next scene

        // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
        // someWhereViewController.output.name = viewController.output.name
    }
}
