//
//  ListTakesRouter.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-04-08.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListTakesRouterInput
{
  func navigateToDisplayTakeScene(listTakesViewModel: ListTakes.FetchTakes.ViewModel.DisplayedTake)
}

class ListTakesRouter: ListTakesRouterInput
{
  weak var viewController: ListTakesViewController!
  
  // MARK: - Navigation
  
  func navigateToDisplayTakeScene(listTakesViewModel: ListTakes.FetchTakes.ViewModel.DisplayedTake)
  {
    let displayTakeViewModel = DisplayTake.ViewModel(author: listTakesViewModel.author,
                                                     numberOfVotes: listTakesViewModel.numberOfVotes,
                                                     likeButtonImage: listTakesViewModel.likeButtonImage,
                                                     takeImage: listTakesViewModel.takeImage)
    let dtvc = DisplayTakeViewController(viewModel: displayTakeViewModel)
    viewController.navigationController?.pushViewController(dtvc, animated: true)
    
  }
  
  // MARK: - Communication
  
  func passDataToNextScene(segue: UIStoryboardSegue)
  {
    // NOTE: Teach the router which scenes it can communicate with
    
    if segue.identifier == "ShowSomewhereScene" {
      passDataToSomewhereScene(segue: segue)
    }
  }
  
  func passDataToSomewhereScene(segue: UIStoryboardSegue)
  {
    // NOTE: Teach the router how to pass data to the next scene
    
    // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
    // someWhereViewController.output.name = viewController.output.name
  }
}
