//
//  ListTakesModels.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-04-08.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ListTakes {
    
    struct FetchTakes {
        
        struct Request {
            var challengeId: String
        }
        
        struct Response {
            var takes: [TakeDto]
            var votedForTakeId: String?
        }
        
        struct ViewModel {
            struct DisplayedTake {
                var author: String
                var numberOfVotes: String
                var likeButtonImage: UIImage
                var takeImage: UIImage
            }
            
            var displayedTakes: [DisplayedTake]
        }
    }
    
    struct VoteForTake {
        
        struct Request {
            var takeTag: Int
        }
        
        struct Response {
            var votedForTakeId: String?
        }
    }
}
