//
//  ListTakesConfigurator.swift
//  YourTake
//
//  Created by John Buonassisi on 2017-04-08.
//  Copyright (c) 2017 Enovi Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ListTakesViewController: ListTakesPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension ListTakesInteractor: ListTakesViewControllerOutput
{
}

extension ListTakesPresenter: ListTakesInteractorOutput
{
}

class ListTakesConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ListTakesConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ListTakesViewController)
  {
    let router = ListTakesRouter()
    router.viewController = viewController
    
    let presenter = ListTakesPresenter()
    presenter.output = viewController
    
    let interactor = ListTakesInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
